<a href="https://colab.research.google.com/github/Qureshiii/PyTorch-Learning-Journey/blob/main/03_Neural_Network_Breast_Cancer_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [25]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-detection/refs/heads/master/data.csv')

In [26]:
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,radius_se,texture_se,perimeter_se,area_se,smoothness_se,compactness_se,concavity_se,concave points_se,symmetry_se,fractal_dimension_se,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,1.0950,0.9053,8.589,153.40,0.006399,0.04904,0.05373,0.01587,0.03003,0.006193,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,0.5435,0.7339,3.398,74.08,0.005225,0.01308,0.01860,0.01340,0.01389,0.003532,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,0.7456,0.7869,4.585,94.03,0.006150,0.04006,0.03832,0.02058,0.02250,0.004571,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,0.4956,1.1560,3.445,27.23,0.009110,0.07458,0.05661,0.01867,0.05963,0.009208,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,0.7572,0.7813,5.438,94.44,0.011490,0.02461,0.05688,0.01885,0.01756,0.005115,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN


In [27]:
df.shape

(569, 33)

In [28]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)

In [29]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,radius_se,texture_se,perimeter_se,area_se,smoothness_se,compactness_se,concavity_se,concave points_se,symmetry_se,fractal_dimension_se,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,1.0950,0.9053,8.589,153.40,0.006399,0.04904,0.05373,0.01587,0.03003,0.006193,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,0.5435,0.7339,3.398,74.08,0.005225,0.01308,0.01860,0.01340,0.01389,0.003532,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,0.7456,0.7869,4.585,94.03,0.006150,0.04006,0.03832,0.02058,0.02250,0.004571,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,0.4956,1.1560,3.445,27.23,0.009110,0.07458,0.05661,0.01867,0.05963,0.009208,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,0.7572,0.7813,5.438,94.44,0.011490,0.02461,0.05688,0.01885,0.01756,0.005115,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678


### Train Test Split

In [30]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

### Scaling

In [31]:
scaler = StandardScaler()

# 1. Train data par fit aur transform dono karein
X_train = scaler.fit_transform(X_train)

# 2. Test data par SIRF transform karein (taaki train wala mean/std hi use ho)
X_test = scaler.transform(X_test)

In [32]:
X_train

array([[-0.47446264, -0.59199807, -0.53533035, ..., -1.3183545 ,
        -1.56799459, -1.21153344],
       [ 0.06984288, -0.97887183,  0.06249377, ...,  0.66198133,
        -0.32840626, -0.38898231],
       [ 1.69438551,  0.83966652,  1.6169174 , ...,  0.62299244,
         1.26992599, -0.01559097],
       ...,
       [-0.58332375, -0.39045305, -0.58063232, ..., -0.79620325,
         0.24494339, -0.71713061],
       [ 0.93514909, -0.01979555,  0.91716386, ...,  1.17183608,
         0.05115761, -0.28868449],
       [-1.02714209,  0.18174946, -0.96205867, ..., -0.8156977 ,
        -0.82167914,  0.34308276]])

In [33]:
y_train

,diagnosis
315,B
148,B
95,M
135,M
563,M
...,...
194,M
354,B
394,B
201,M


### Label Encoding

In [35]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [36]:
y_train

array([0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0,

### Numpy Arrays to PyTorch Tensors

In [37]:
X_train_tensors = torch.from_numpy(X_train)
X_test_tensors = torch.from_numpy(X_test)
y_train_tensors = torch.from_numpy(y_train)
y_test_tensors = torch.from_numpy(y_test)

In [42]:
X_train_tensors.shape

torch.Size([455, 30])

In [41]:
y_train_tensors.shape

torch.Size([455])

### Defining the Model

In [75]:
import torch.nn as nn
import torch.optim as optim


class MySimpleNN(nn.Module):
  def __init__(self, X):
        super(MySimpleNN, self).__init__()  # nn.Module ko initialize karna zaroori hai

        # Weights aur Bias ko nn.Parameter banana padega taaki model.parameters() kaam kare
        self.weights = nn.Parameter(torch.rand(X.shape[1], 1, dtype=torch.float64))
        self.bias = nn.Parameter(torch.zeros(1, dtype=torch.float64))


  def forward(self,X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred


  def loss_function(self,y_pred,y):
    # Clamp prediction to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)
    # caluculate loss
    loss = - (y * torch.log(y_pred) + (1 - y) * torch.log(1 - y_pred)).mean()
    return loss

### Important Parameters

In [107]:
learning_rate = 0.05
epochs = 1000

### Training Pipeline

In [108]:
# Create model
model = MySimpleNN(X_train_tensors)

# Ab optimizer define karein (Ab model.parameters() perfectly kaam karega)
optimizer = optim.SGD(model.parameters(), lr=0.01)

# define in loop = epochs
for epochs in range(epochs):
# forward pass
  y_pred = model.forward(X_train_tensors)

# loss calculate
  loss = model.loss_function(y_pred, y_train_tensors)

# bachward pass
  loss.backward()

# parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

# Zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

# print loss in each epochs
  print(f'Epochs : {epochs + 1}, loss : {loss.item()}')

Epochs : 1, loss : 3.8684788357905466
Epochs : 2, loss : 3.814148735676385
Epochs : 3, loss : 3.758799806484897
Epochs : 4, loss : 3.702180896733847
Epochs : 5, loss : 3.6449418728414487
Epochs : 6, loss : 3.5858699789364583
Epochs : 7, loss : 3.526592359662895
Epochs : 8, loss : 3.466785040844942
Epochs : 9, loss : 3.4055244695394764
Epochs : 10, loss : 3.3443372240045433
Epochs : 11, loss : 3.2822872017002
Epochs : 12, loss : 3.2190626185630236
Epochs : 13, loss : 3.154640197664081
Epochs : 14, loss : 3.0900498364302544
Epochs : 15, loss : 3.0248038280620615
Epochs : 16, loss : 2.957934605266771
Epochs : 17, loss : 2.8869398464793417
Epochs : 18, loss : 2.8145539833262374
Epochs : 19, loss : 2.741266218640236
Epochs : 20, loss : 2.6664775148853295
Epochs : 21, loss : 2.592129999507895
Epochs : 22, loss : 2.516849017087743
Epochs : 23, loss : 2.440438268408784
Epochs : 24, loss : 2.3624465776022032
Epochs : 25, loss : 2.284629396678558
Epochs : 26, loss : 2.205383244006523
Epochs : 27

In [109]:
model.bias

Parameter containing:
tensor([-0.5191], dtype=torch.float64, requires_grad=True)

### Model Evaluation

In [118]:
with torch.no_grad():
    y_pred = model.forward(X_test_tensors)

    # Threshold ko 0.5 karein (Standard Binary Classification rule)
    y_pred = (y_pred >= 0.5).float()

    accuracy = (y_pred == y_test_tensors).float().mean()
    print(f'Model Accuracy : {accuracy.item() * 100:.2f}%')


Model Accuracy : 53.69%


Improve model Accuracy

In [111]:
import torch
import torch.nn as nn
import torch.optim as optim

class MyUpgradedNN(nn.Module):
    def __init__(self, input_dim):
        super(MyUpgradedNN, self).__init__()
        # Input layer se Hidden layer (16 neurons)
        self.fc1 = nn.Linear(input_dim, 16)
        # Hidden layer se Output layer (1 neuron)
        self.fc2 = nn.Linear(16, 1)

    def forward(self, X):
        # Hidden layer ke baad non-linear ReLU activation
        x = torch.relu(self.fc1(X))
        # Final output ke liye Sigmoid function
        y_pred = torch.sigmoid(self.fc2(x))
        return y_pred


In [115]:
# 1. Input dimensions pata karein (Aapke features ki ginti)
input_dim = X_train_tensors.shape[1]

# 2. Model, Loss aur Optimizer initialize karein
model = MyUpgradedNN(input_dim).double()
criterion = nn.BCELoss()  # PyTorch ka standard Binary Cross Entropy Loss
optimizer = optim.Adam(model.parameters(), lr=0.005)  # Adam optimizer standard SGD se fast hai

# 3. Epochs ko badha kar 1000 ya 1500 karein
num_epochs = 1000

for epoch in range(num_epochs):
    # Forward Pass
    y_pred = model(X_train_tensors)

    # Loss Calculation
    loss = criterion(y_pred, y_train_tensors.unsqueeze(1).double())

    # Backward Pass aur Weights Update
    optimizer.zero_grad()  # Pichle gradients saaf karein
    loss.backward()        # Backpropagation
    optimizer.step()       # Weights update karna

    # Har 100 epochs baad loss print karein
    if (epoch + 1) % 100 == 0:
        print(f'Epoch: {epoch + 1}/{num_epochs}, Loss: {loss.item():.4f}')


Epoch: 100/1000, Loss: 0.0545
Epoch: 200/1000, Loss: 0.0351
Epoch: 300/1000, Loss: 0.0234
Epoch: 400/1000, Loss: 0.0146
Epoch: 500/1000, Loss: 0.0094
Epoch: 600/1000, Loss: 0.0064
Epoch: 700/1000, Loss: 0.0047
Epoch: 800/1000, Loss: 0.0037
Epoch: 900/1000, Loss: 0.0031
Epoch: 1000/1000, Loss: 0.0026


In [117]:
with torch.no_grad():
    # 1. Test data par prediction lein
    y_pred_test = model(X_test_tensors)

    # 2. Threshold 0.5 set karein
    y_pred_class = (y_pred_test >= 0.5).float()

    # 3. Target ko unsqueeze karke exact same shape (2D) me compare karein
    accuracy = (y_pred_class == y_test_tensors.unsqueeze(1)).float().mean()

    print(f'Upgraded Model Accuracy : {accuracy.item() * 100:.2f}%')


Upgraded Model Accuracy : 97.37%
